---
- name: Block for error handling
  vars:
    service_name: "{{ notdefined | mandatory }}"
    service_workloads: "{{ notdefined | mandatory }}"
  block:
    - name: Set service mode
      ansible.builtin.set_fact:
        "{{ service_name }}_mode": "{{ service_mode | default('install') }}"

    - name: Run service role
      ansible.builtin.include_role:
        name: depin.services.{{ service_name }}
  rescue:
    - name: Continue on error
      ansible.builtin.debug:
        msg: "Issue during {{ service_name }} {{ vars[service_name + '_mode'] }} of {{ service_workloads }}..."
