- name: Manage VM Services
  hosts: localhost
  gather_facts: true
  vars:
    device_short_hostname: "{{ lookup('pipe', 'hostname -s') }}"
    _filter: "status=active cluster={{ device_short_hostname | split('-') | last }}"
    services: "{{ query('depin.libs.netbox', 'ipam.services', filter=_filter) }}"
  tasks:
    - name: Install required services
      ansible.builtin.include_role:
        name: depin.core.manager
