- name: Gather info
  ansible.builtin.include_tasks:
    file: asserts_info.yml

- name: Check service facts
  vars:
    _name: "{{ item['stat']['path'] | basename }}"
  when:
    - item['stat']['exists']
  ansible.builtin.assert:
    that:
      - ansible_facts['services'][_name] is defined
      - ansible_facts['services'][_name]['state'] == 'running'
      - ansible_facts['services'][_name]['status'] == 'enabled'
    quiet: true
  loop: "{{ _service_file['results'] }}"
  loop_control:
    label: "{{ item['stat']['path'] | basename }}"

- name: Check common stats
  ansible.builtin.assert:
    that:
      - item['stat']['exists']
    quiet: true
  loop: "{{ _binary_file['results'] + _program_dir['results'] + _service_file['results'] }}"
  loop_control:
    label: "{{ item['stat']['path'] }}"

- name: Check pids
  ansible.builtin.assert:
    that:
      - item['pids'] | length > 0
    quiet: true
  loop: "{{ service_pids['results'] }}"
  loop_control:
    label: "{{ item['invocation']['module_args']['name'] }}"
