#cloud-config
packages:
  - acl
  - nano
  - curl
  - jq
  - unzip
package_upgrade: true
package_update: true

users:
  - name: nerdnode
    gecos: NerdNode Admin Account
    groups: users,admin,wheel
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: true
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOEu3Yh+xr+oNfcj72bcqcZNhg3D1SzeHh+BQKX4/05V anthony@nerdnode.io