---
- name: Stop node
  become: true
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: false
    state: stopped
  loop: "{{ storagechain_programs }}"

- name: Assert
  when: "'molecule' in groups"
  block:
    - name: Get service facts
      ansible.builtin.service_facts:
    
    - name: Check service facts
      vars:
        _name: "{{ item }}.service"
      ansible.builtin.assert:
        that:
          - ansible_facts['services'][_name] is defined
          - ansible_facts['services'][_name]['state'] == 'stopped'
          - ansible_facts['services'][_name]['status'] == 'disabled'
        quiet: true
      loop: "{{ storagechain_programs }}"
