---
- name: Disable systemd service
  ansible.builtin.include_tasks: commands/stop.yml

- name: Uninstall dependencies
  vars:
    service_cmd: uninstall # should be set but if not
  ansible.builtin.include_role:
    name: "{{ item }}"
  loop:
    - depin.libs.ipfs_cluster_follow
    - depin.libs.ipfs

- name: Uninstall
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
    force: true
  loop:
    - /usr/local/bin/file-server-lin
    - /opt/{{ role_name }}
    - /etc/systemd/system/file-server-lin.service

- name: Assert
  when: "'molecule' in groups"
  block:
    # relative to playbook (molecule - default)
    - name: Common uninstall asserts
      ansible.builtin.include_tasks:
        file: tasks/asserts_uninstall.yml

    - name: Get unique stats
      become: true
      ansible.builtin.stat:
        path: /home/ipfs/.{{ item }}
        follow: true
      loop:
        - ipfs
        - ipfs-cluster-follow
      register: _unique_stats

    - name: Check unique stats
      ansible.builtin.assert:
        that:
          - not {{ item['stat']['exists']
        quiet: true
      loop: "{{ _unique_stats['results'] }}"
      loop_control:
        label: "{{ item['stat']['path'] }}"