---
- name: Setup Development Environment
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Install signed DePIN Collections
      ansible.builtin.include_role:
        name: depin.utils.signed_collection
