---
- name: Setup Development Environment
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Install SOPS
      vars:
        sops_install_on_localhost: true # noqa var-naming[no-role-prefix]
        sops_version: 3.9.0
      when: ansible_facts.distribution != 'MacOSX'
      ansible.builtin.include_role:
        name: community.sops.install

    - name: Install SOPS
      when: ansible_facts.distribution == 'MacOSX'
      community.general.homebrew:
        name:
          - sops
          - gnupg
        state: latest
        update_homebrew: true

    # - name: Install collections
    #   block:
    #     - name: Download zip file
    #       ansible.builtin.archive:

    #     - name: Install collections and roles together
    #       community.general.ansible_galaxy_install:
    #         type: both
    #         requirements_file: /tmp/deeep-collections/requirements.yml
