---
- name: Converge
  hosts: molecule
  gather_facts: true
  tasks:
     # install (start)
    - name: Install
      ansible.builtin.include_role:
        name: "{{ test_role | default('depin.utils.test') }}"
        tasks_from: commands/install.yml

    # reset - uninstall (stop) and install (start)
    - name: Reset
      ansible.builtin.include_role:
        name: "{{ test_role | default('depin.utils.test') }}"
        tasks_from: commands/reset.yml

    # restart
    - name: Restart
      when: systemd_managed
      ansible.builtin.include_role:
        name: "{{ test_role | default('depin.utils.test') }}"
        tasks_from: commands/restart.yml
