---
driver:
  name: default
dependency:
  name: galaxy
platforms:
  - name: instance
    image: ubuntu:noble
provisioner:
  name: ansible
  playbooks:
    create: ../shared/substrate/${MOLECULE_SUBSTRATE:-orbstack}/create.yml
    destroy: ../shared/substrate/${MOLECULE_SUBSTRATE:-orbstack}/destroy.yml
    prepare: ../shared/prepare.yml
  inventory:
    links:
      hosts: ../shared/inventory/
      group_vars: ../shared/group_vars/
