---
driver:
  name: libvirt
dependency:
  name: galaxy
  options:
    requirements-file: ../../requirements.yml
platforms:
  - name: instance
    image: ubuntu:20.04
    user: ansible
provisioner:
  name: ansible
  playbooks:
    create: ../substrate/kvm/create.yml
    destroy: ../substrate/kvm/destroy.yml
    prepare: ../substrate/kvm/prepare.yml
  inventory:
    links:
      hosts: ../inventory/
