---
driver:
  name: default
dependency:
  name: galaxy
platforms:
  - name: instance
    image: ubuntu:noble
provisioner:
  name: ansible
  playbooks:
    create: ../substrate/${MOLECULE_SUBSTRATE:-kvm}/create.yml
    destroy: ../substrate/${MOLECULE_SUBSTRATE:-kvm}/destroy.yml
  inventory:
    links:
      hosts: ../inventory/
      group_vars: ../group_vars/
