---
- name: Update presearch docker node
  hosts: all
  become: true

  vars:
      docker_container_version: "1.2.34"

  tasks:
    - name: Stop an image
      community.docker.docker_container:
        state: stopped
        name: presearch

    - name: Remove an image
      community.docker.docker_container:
        state: absent
        name: presearch

    - name: Pull an image
      community.docker.docker_container:
        state: present
        name: presearch
        image: presearch/node:{{ docker_container_version }}

    - name: Start a container with a command
      community.docker.docker_container:
        name: presearch
        state: started
        restart: true
        image:  presearch/node:{{ docker_container_version }}
        restart_policy: unless-stopped
        volumes:
          - presearch-node-storage:/app/node
        env:
          REGISTRATION_CODE: "{{ presearch_reg_code }}"
