---
- name: Destroy molecule VMs
  hosts: molecule
  gather_facts: false
  tasks:
    - name: Destroy KVM VM
      delegate_to: localhost
      community.libvirt.virt:
        name: "{{ inventory_hostname }}"
        state: absent
      changed_when: true
      failed_when: false

- name: Remove dynamic molecule inventory
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Remove dynamic inventory file
      ansible.builtin.file:
        path: ../../inventory/molecule_inventory.yml
        state: absent

    - name: Remove molecule group from inventory
      ansible.builtin.set_fact:
        molecule_inventory: "{{ molecule_inventory | combine({'molecule': {'hosts': {}}}, recursive=true) }}"
      when: molecule_inventory is defined

    - name: Remove inventory file if empty
      ansible.builtin.file:
        path: ../../inventory/molecule_inventory.yml
        state: absent
      when: molecule_inventory is defined and molecule_inventory.molecule.hosts is defined and molecule_inventory.molecule.hosts | length == 0

