---
- name: Destroy molecule VMs
  hosts: molecule
  gather_facts: false
  tasks:
    - name: Destroy KVM VM
      delegate_to: localhost
      community.libvirt.libvirt_vm:
        name: "{{ inventory_hostname }}"
        state: absent
      changed_when: false
      failed_when: false

- name: Remove dynamic molecule inventory
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Remove dynamic inventory file
      ansible.builtin.file:
        path: ../../inventory/molecule_inventory.yml
        state: absent
