---
- name: Restart File Server
  become: true
  ansible.builtin.systemd_service:
    name: file-server-lin
    daemon_reload: true
    enabled: true
    state: restarted
  listen: restart file-server-lin
