---
## install dependencies and service


- name: Start
  ansible.builtin.include_tasks: commands/start.yml

- name: Install metrics
  vars:
    depin_cmd: install
  ansible.builtin.include_tasks:
    file: tasks/metrics.yml

# @todo - assert correct version installed
# relative to playbook (molecule - default)
- name: Assert Install
  when: "'molecule' in groups"
  block:
    - name: Common install asserts
      ansible.builtin.include_tasks:
        file: tasks/asserts_install.yml

    # unique asserts go here
