---
- name: Disable systemd service
  ansible.builtin.include_tasks: commands/stop.yml

- name: Uninstall metrics
  vars:
    depin_cmd: uninstall
  ansible.builtin.include_tasks:
    file: tasks/metrics.yml

## uninstall service and remove all associated files

# relative to playbook (molecule - default)
- name: Assert Uninstall
  when: "'molecule' in groups"
  block:
    - name: Common install asserts
      ansible.builtin.include_tasks:
        file: tasks/asserts_uninstall.yml

    # unique asserts go here
