---
storagechain_cmd: "{{ depin_cmd | default('install') }}"
storagechain_credentials: "{{ service_credentials }}"

storagechain_ipfs_cluster_type: service
storagechain_programs:
  - ipfs
  - ipfs-cluster-{{ storagechain_ipfs_cluster_type }}
  - file-server-lin

storagechain_download_urls:
  - https://file-view-prod.storagechain.io/api/file/download/QRFhcWOyVN9IqxdOYmhQh2K84iqhMo9O
# storagechain_ipfs_checksum: 47af81af0c1c0aeb26e879cf3b5e548ae9a9ff56
# storagechain_ipfs_cluster_checksum: 144ae74c02d86be5c13c38c6da4358f4769de842
storagechain_ipfs_cluster_remote_config: http://94.72.127.176:8080/ipns/k51qzi5uqu5dlb5l2sctf6csb72qmcs70u0y454vmsgu6w38jd9fdqb7155wjg

storagechain_version: v3.1.5
storagechain_dir: /opt/storagechain/{{ storagechain_version }}

storagechain_ipfs_cluster_args: "{{ storagechain_email }}:{{ storagechain_password }}:{{ storagechain_node_id }}"
storagechain_cluster_secret: a89fe67688f00ee7cb5eb25084f9971174433cd15a6349783a2c268b8bed730a
storagechain_default_dns: "{{ storagechain_node_id }}.sc.nerdnode.io"

storagechain_node_name: "{{ storagechain_credentials['custom_fields']['custom_name'] }}"
storagechain_node_id: "{{ storagechain_credentials['custom_fields']['nodeid'] }}"
storagechain_email: "{{ storagechain_credentials['custom_fields']['username'] }}"
storagechain_dns: "{{ storagechain_credentials['custom_fields']['dns'] | default(storagechain_default_dns) }}"
storagechain_password: "{{ storagechain_credentials['plaintext'] }}"
storagechain_node_size: "{{ service_vm['disk'] }}GB"

storagechain_firewall:
  protocol:
    value: tcp
  ports:
    - 3008
    - 4001
    - 5001
    - 8080
    - 9094
    - 9095
    - 9096

storagechain_metrics_port: 33004
