---
- name: Create
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Delete and purge a VM
      vars:
        _vm: "{{ molecule_yml['platforms'] | first }}"
      theko2fi.multipass.multipass_vm:
        name: "{{ _vm['name'] }}"
        state: absent
        purge: true

    - name: Remove dynamic inventory file
      ansible.builtin.file:
        path: ../../inventory/molecule_inventory.yml
        state: absent
