---
driver:
  name: default
dependency:
  name: galaxy
  options:
    requirements-file: ../../../requirements.yml
platforms:
  - name: instance
    image: quay.io/centos/centos:stream8
provisioner:
  name: ansible
  playbooks:
    create: ../../../shared-tests/playbooks/create.yml
    destroy: ../../../shared-tests/playbooks/destroy.yml
    prepare: ../../../shared-tests/playbooks/prepare.yml